version: '3.1'
services:
  web:
    image: hirichardhai/product-reviews:latest
    ports:
      - 5432:5432
      - 80:80
    environment:
      DB_HOST: postgres://student:student@db/etsy-richard
      PORT: 80

  db:
    image: postgres:10.2
    environment:
      POSTGRES_USER: student
      POSTGRES_DB: etsy-richard
      POSTGRES_PW: student
